# Generated by Django 4.2.7 on 2023-11-22 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import func_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('', 'Не указан'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], default='', max_length=6, verbose_name='Зима')),
                ('summer', models.CharField(choices=[('', 'Не указан'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], default='', max_length=6, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('', 'Не указан'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], default='', max_length=6, verbose_name='Осень')),
                ('spring', models.CharField(choices=[('', 'Не указан'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], default='', max_length=6, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('fam', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('otc', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'на модерации'), ('accepted', 'принят'), ('rejected', 'не принят')], default='NW', max_length=8)),
                ('beauty_title', models.CharField(default='пер.', max_length=255, verbose_name='Название топонима')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('other_titles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другое название')),
                ('connect', models.TextField(blank=True, null=True, verbose_name='Что связывает')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('coords', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pass.coords')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pass.level')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pass.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=func_path.get_image_path, verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('mountain_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pass.mountainpass')),
            ],
        ),
    ]
